---
name: Build Image
on:
  push:
    branches:
      - 'gh-actions'

env:
  IMAGE_NAME: cop-platform-tools
  IMAGE_REPO: quay.io/ukhomeofficedigital

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get date and time
        id: date
        run: echo "::set-output name=datetime::$(date +%Y%m%d%H%M)"

      - name: Build ${{ env.IMAGE_NAME }} container image
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: false
          tags: ${{ env.IMAGE_NAME }}.${{ steps.date.outputs.datetime }}
